export const resources = [
	{
		kind: 111,
		image: "images/resources/construction-units.png",
		price: 2330,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 53,
		image: "images/resources/economy-e-car.png",
		price: 3310,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 135,
		image: "images/resources/sugar.png",
		price: 16.8,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 69,
		image: "images/resources/golden-bars.png",
		price: 6250,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 35,
		image: "images/resources/software.png",
		price: 139,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 86,
		image: "images/resources/rocket-engine.png",
		price: 11500,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 103,
		image: "images/resources/cement.png",
		price: 5.5,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 119,
		image: "images/resources/coffee-ground.png",
		price: 29.75,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 118,
		image: "images/resources/coffee-beans.png",
		price: 0.765,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 22,
		image: "images/resources/batteries.png",
		price: 85,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 136,
		image: "images/resources/cocoa-beans.png",
		price: 1.5,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 60,
		image: "images/resources/underwear.png",
		price: 4.75,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 21,
		image: "images/resources/electronic-components.png",
		price: 54.5,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 68,
		image: "images/resources/gold-ore.png",
		price: 30.75,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 75,
		image: "images/resources/carbon-fiber.png",
		price: 6.5,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 9,
		image: "images/resources/eggs.png",
		price: 1,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 13,
		image: "images/resources/transport.png",
		price: 0.348,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 145,
		image: "images/resources/recipes.png",
		price: 204,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 6,
		image: "images/resources/grain.png",
		price: 0.555,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 14,
		image: "images/resources/minerals.png",
		price: 10.9,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 34,
		image: "images/resources/chemistry-research.png",
		price: 141,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 44,
		image: "images/resources/sand.png",
		price: 1.15,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 11,
		image: "images/resources/petrol.png",
		price: 39,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 122,
		image: "images/resources/cheese.png",
		price: 126,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 28,
		image: "images/resources/televisions.png",
		price: 875,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 1,
		image: "images/resources/power.png",
		price: 0.235,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 85,
		image: "images/resources/solid-rocket.png",
		price: 8425,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 30,
		image: "images/resources/energy-research.png",
		price: 258,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 20,
		image: "images/resources/processors.png",
		price: 120,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 18,
		image: "images/resources/aluminium.png",
		price: 18.8,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 72,
		image: "images/resources/sugarcane.png",
		price: 1.15,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 49,
		image: "images/resources/luxury-car-interior.png",
		price: 880,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 58,
		image: "images/resources/automotive-research.png",
		price: 200,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 2,
		image: "images/resources/water.png",
		price: 0.321,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 84,
		image: "images/resources/fuel-tank.png",
		price: 8800,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 8,
		image: "images/resources/sausages.png",
		price: 9.5,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 66,
		image: "images/resources/seeds.png",
		price: 0.219,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 115,
		image: "images/resources/cow.png",
		price: 108,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 4,
		image: "images/resources/oranges.png",
		price: 1.9,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 32,
		image: "images/resources/electronics-research.png",
		price: 360,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 102,
		image: "images/resources/bricks.png",
		price: 2.2,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 73,
		image: "images/resources/ethanol.png",
		price: 23.5,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 29,
		image: "images/resources/plant-research.png",
		price: 139,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 25,
		image: "images/resources/tablets.png",
		price: 700,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 42,
		image: "images/resources/iron-ore.png",
		price: 4.7,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 113,
		image: "images/resources/materials-research.png",
		price: 199,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 47,
		image: "images/resources/on-board-computer.png",
		price: 438,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 126,
		image: "images/resources/ginger-beer.png",
		price: 43.75,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 124,
		image: "images/resources/orange-juice.png",
		price: 28.25,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 40,
		image: "images/resources/cotton.png",
		price: 1.25,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 15,
		image: "images/resources/bauxite.png",
		price: 9.3,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 3,
		image: "images/resources/apples.png",
		price: 1.89,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 79,
		image: "images/resources/high-grade-e-components.png",
		price: 880,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 16,
		image: "images/resources/silicon.png",
		price: 7.7,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 125,
		image: "images/resources/apple-cider.png",
		price: 21.25,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 5,
		image: "images/resources/grapes.png",
		price: 2.3,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 130,
		image: "images/resources/lasagna.png",
		price: 2140,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 87,
		image: "images/resources/heat-shield.png",
		price: 400,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 10,
		image: "images/resources/crude-oil.png",
		price: 27.75,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 77,
		image: "images/resources/fuselage.png",
		price: 2710,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 121,
		image: "images/resources/bread.png",
		price: 169,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 76,
		image: "images/resources/carbon-composite.png",
		price: 60.5,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 83,
		image: "images/resources/rocket-fuel.png",
		price: 30.75,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 43,
		image: "images/resources/steel.png",
		price: 10.9,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 45,
		image: "images/resources/glass.png",
		price: 12.9,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 108,
		image: "images/resources/planks.png",
		price: 9.1,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 139,
		image: "images/resources/fodder.png",
		price: 8.5,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 31,
		image: "images/resources/mining-research.png",
		price: 286,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 133,
		image: "images/resources/flour.png",
		price: 12.7,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 33,
		image: "images/resources/breeding-research.png",
		price: 175,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 112,
		image: "images/resources/bulldozer.png",
		price: 2030,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 50,
		image: "images/resources/car-interior.png",
		price: 300,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 46,
		image: "images/resources/leather.png",
		price: 20.25,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 7,
		image: "images/resources/steak.png",
		price: 35.75,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 23,
		image: "images/resources/displays.png",
		price: 119,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 134,
		image: "images/resources/butter.png",
		price: 47,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 120,
		image: "images/resources/vegetables.png",
		price: 2.05,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 17,
		image: "images/resources/chemicals.png",
		price: 14.2,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 129,
		image: "images/resources/hamburger.png",
		price: 2090,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 105,
		image: "images/resources/limestone.png",
		price: 1.32,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 74,
		image: "images/resources/methane.png",
		price: 19.4,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 12,
		image: "images/resources/diesel.png",
		price: 39,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 109,
		image: "images/resources/windows.png",
		price: 97,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 110,
		image: "images/resources/tools.png",
		price: 178,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 41,
		image: "images/resources/fabric.png",
		price: 3.95,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 82,
		image: "images/resources/attitude-control.png",
		price: 1680,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 100,
		image: "images/resources/aero-research.png",
		price: 300,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 59,
		image: "images/resources/fashion-research.png",
		price: 103,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 114,
		image: "images/resources/robots.png",
		price: 240,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 26,
		image: "images/resources/laptops.png",
		price: 1090,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 106,
		image: "images/resources/wood.png",
		price: 3,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 89,
		image: "images/resources/jet-engine.png",
		price: 4840,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 101,
		image: "images/resources/reinforced-concrete.png",
		price: 168,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 104,
		image: "images/resources/clay.png",
		price: 0.79,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 56,
		image: "images/resources/luxury-car.png",
		price: 4180,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 55,
		image: "images/resources/economy-car.png",
		price: 2170,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 131,
		image: "images/resources/meatballs.png",
		price: 2200,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 107,
		image: "images/resources/steel-beams.png",
		price: 18.4,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 51,
		image: "images/resources/car-body.png",
		price: 730,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 64,
		image: "images/resources/handbags.png",
		price: 35.75,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 52,
		image: "images/resources/combustion-engine.png",
		price: 600,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 137,
		image: "images/resources/dough.png",
		price: 112,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 19,
		image: "images/resources/plastic.png",
		price: 10.4,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 117,
		image: "images/resources/milk.png",
		price: 6.3,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 140,
		image: "images/resources/chocolate.png",
		price: 250,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 61,
		image: "images/resources/gloves.png",
		price: 14.5,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 48,
		image: "images/resources/electric-motor.png",
		price: 214,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 127,
		image: "images/resources/pizza.png",
		price: 446,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 138,
		image: "images/resources/gravy-boat.png",
		price: 1330,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 88,
		image: "images/resources/ion-drive.png",
		price: 11400,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 24,
		image: "images/resources/smart-phones.png",
		price: 580,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 78,
		image: "images/resources/wing.png",
		price: 1940,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 116,
		image: "images/resources/pig.png",
		price: 34.5,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 54,
		image: "images/resources/luxury-e-car.png",
		price: 6200,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 57,
		image: "images/resources/truck.png",
		price: 5450,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 98,
		image: "images/resources/quadcopter.png",
		price: 815,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 65,
		image: "images/resources/sneakers.png",
		price: 12.3,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 63,
		image: "images/resources/simmi-shoes.png",
		price: 27,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 144,
		image: "images/resources/xmas-ornament.png",
		price: 30,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 142,
		image: "images/resources/salad.png",
		price: 720,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 132,
		image: "images/resources/cocktails.png",
		price: 2150,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 62,
		image: "images/resources/dress.png",
		price: 17.7,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 123,
		image: "images/resources/apple-pie.png",
		price: 258,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 80,
		image: "images/resources/flight-computer.png",
		price: 4850,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 81,
		image: "images/resources/cockpit.png",
		price: 5200,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 143,
		image: "images/resources/samosas.png",
		price: 565,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 27,
		image: "images/resources/monitors.png",
		price: 535,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 71,
		image: "images/resources/necklace.png",
		price: 1550,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 70,
		image: "images/resources/gold-watch.png",
		price: 740,
		is_up: false,
		realmId: 0,
	},
	{
		kind: 141,
		image: "images/resources/vegetable-oil.png",
		price: 30,
		is_up: true,
		realmId: 0,
	},
	{
		kind: 128,
		image: "images/resources/pasta.png",
		price: 45,
		is_up: true,
		realmId: 0,
	},
];
